name: Terraform Deploy - CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.6.6"
  AWS_REGION: us-east-1
  WORKING_DIRECTORY: ci-cd

jobs:
  plan:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy IaC Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "config"
          scan-ref: ${{ env.WORKING_DIRECTORY }}
          format: "table"
          exit-code: "0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -input=false -backend-config=backend/dev.hcl

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=tfvars/dev.tfvars -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-cicd
          path: ${{ env.WORKING_DIRECTORY }}/tfplan
          retention-days: 1

  apply:
    name: Terraform Apply (Manual Approval)
    needs: plan
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -input=false -backend-config=backend/dev.hcl

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-cicd
          path: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
