name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Validate & Plan
    uses: your-org/your-repo/.github/workflows/terraform-reusable-ci.yml@main
    with:
      working_directory: eks
      aws_region: us-east-1
      terraform_version: "1.6.6"
      role_to_assume: arn:aws:iam::165369967212:role/github-terraform
      apply: false

  apply:
    name: Terraform Apply (Manual Approval)
    needs: plan
    uses: your-org/your-repo/.github/workflows/terraform-apply.yml@main
    with:
      working_directory: eks
      aws_region: us-east-1
      terraform_version: "1.6.6"
      role_to_assume: arn:aws:iam::165369967212:role/github-terraform
      environment: prod
